// Shared data for OhMyGlass prototype
window.OMG_DATA = {
  services: {
    emergency: [
      { badge: '24/7', title: 'Emergency Glass Repair', desc: '24/7 emergency service for broken or shattered glass. Fast response, professional repair, and cost-effective solutions. Don\'t replace when we can repair!', link: '/emergency-glass-repair' },
    ],
    residential: [
      { badge: 'FAST', title: 'Broken Window Repair', desc: 'Fast and safe repair of broken windows. Save 60-80% compared to replacement. Professional assessment to determine the best solution for your damage.' },
      { badge: 'REPAIR', title: 'Residential Window Repair', desc: 'Complete repair services for all types of residential windows. Save 60-80% vs replacement with professional repair techniques.' },
      { badge: 'TORONTO', title: 'Window Repair Toronto', desc: 'Same-day window repair in Toronto for cracked, broken, and foggy glass. Repair-first service that saves 60-80% vs replacement.' },
      { badge: 'NORTH YORK', title: 'Window Repair North York', desc: 'Fast and affordable window repair in North York for homes, condos, and businesses. 24/7 emergency response available.' },
      { badge: 'REPAIR', title: 'Foggy Window Repair', desc: 'Restore clarity to your insulated windows with our professional defogging and seal repair services. Save 60-80% vs replacement.' },
      { badge: null, title: 'Door Repairs', desc: 'Door glass repair and replacement for patio doors, entry doors, and sliding glass doors. Save 60-80% with repair when possible.' },
      { badge: null, title: 'Shower Glass Repair', desc: 'Repair and replacement for frameless enclosures, sliding shower doors, and hinged panels.' },
      { badge: null, title: 'Patio Door Repair', desc: 'Glass panel replacement and hardware repair for sliding and hinged patio doors. Same-day service.' },
      { badge: null, title: 'Sliding Door Repair', desc: 'Track, roller, glass, and hardware repair for residential and commercial sliding doors.' },
      { badge: null, title: 'Window Glass Replacement', desc: 'Upgrade your home or business with our high-quality window glass replacement services.' },
      { badge: 'TORONTO', title: 'Glass Replacement Toronto', desc: 'Expert glass replacement in Toronto for residential and commercial windows with same-day options and clear pricing.' },
      { badge: null, title: 'Double Pane Window Replacement', desc: 'Improve energy efficiency and comfort with our expert double-pane window replacements.' },
    ],
    commercial: [
      { badge: 'REPAIR', title: 'Commercial Glass Repair', desc: 'Reliable glass repair for storefronts, offices, and other commercial properties. Professional repair saves 60-80% vs replacement.' },
      { badge: 'REPAIR', title: 'Storefront Glass Repair', desc: 'Professional storefront glass repair services. Keep your business looking its best with cost-effective repair solutions.' },
      { badge: null, title: 'Aluminum Storefront', desc: 'Aluminum storefront glass repair and installation for commercial spaces. Durable frames, tempered glass, and professional installation across the GTA.' },
    ],
    more: [
      { badge: 'REPAIR', title: 'Window & Door Hardware Repair', desc: 'Expert repair for handles, locks, hinges, and more for all types of windows and doors.' },
      { badge: null, title: 'Custom Mirror', desc: 'Custom mirror installation and repair. Cut to size for bathrooms, closets, and commercial spaces. Professional finish across the GTA.' },
      { badge: null, title: 'Glass Repair vs Window Glass Replacement', desc: 'Replace just the glass (~$200) or full window (~$2k). We replace panes and IGUs — no crack-filling. Expert assessment across the GTA.' },
    ],
  },
  areas: [
    { name: 'Toronto', pop: '2.79M', jobs: '1,800+', eta: '20–40 MIN', desc: 'Full downtown, midtown, east and west end coverage. Our flagship service area with the highest job volume.' },
    { name: 'North York', pop: '869K', jobs: '1,200+', eta: '15–30 MIN', desc: 'Home base. HQ at 7 Benjamin Boake Trail. Fastest response times in the GTA.' },
    { name: 'Vaughan', pop: '323K', jobs: '420+', eta: '30–50 MIN', desc: 'Full coverage including Maple, Woodbridge, Thornhill, Concord. Residential + commercial.' },
    { name: 'Richmond Hill', pop: '202K', jobs: '280+', eta: '35–55 MIN', desc: 'Oak Ridges, Yonge corridor, Bayview. Same-day residential specialty.' },
    { name: 'Markham', pop: '338K', jobs: '310+', eta: '40–60 MIN', desc: 'Unionville, Cathedraltown, Milliken. Strong commercial & office presence.' },
    { name: 'Mississauga', pop: '717K', jobs: '530+', eta: '40–60 MIN', desc: 'Port Credit to Square One. Storefront and high-rise residential.' },
    { name: 'Scarborough', pop: '632K', jobs: '460+', eta: '35–55 MIN', desc: 'Full east GTA coverage. Agincourt, Rouge, Cliffside.' },
    { name: 'Etobicoke', pop: '365K', jobs: '390+', eta: '35–55 MIN', desc: 'Humber Bay, Kipling, Islington. Commercial strips and single-family homes.' },
    { name: 'Newmarket', pop: '84K', jobs: '150+', eta: '50–70 MIN', desc: 'Northern GTA coverage. Scheduled appointments same-week.' },
  ],
  reviews: [
    { stars: 5, text: 'Called at 11pm after a break-in at my shop. Crew was on-site in 35 minutes, boarded everything up, and had new tempered glass in two days. Charged exactly what was quoted.', name: 'Michael R.', meta: 'Storefront · Queen St W', initials: 'MR' },
    { stars: 5, text: 'My double-pane kitchen window cracked in the cold snap. Three other places quoted me a full window replacement. OhMyGlass repaired just the glass for a quarter of the price.', name: 'Priya S.', meta: 'Residential · North York', initials: 'PS' },
    { stars: 5, text: 'Frameless shower enclosure cracked during installation by another company. OhMyGlass came out same-day, measured everything, and replaced the panel perfectly. Saved my reno timeline.', name: 'Derek K.', meta: 'Homeowner · Vaughan', initials: 'DK' },
  ],
  work: [
    { brand: 'Ali Baba\'s', cat: 'Commercial Storefront', desc: 'Replacing glass in a commercial space. Full tempered storefront panel installed in under 4 hours.', loc: 'Toronto', img: 'https://images.unsplash.com/photo-1542321993-8fc36217e26e?w=1200' },
    { brand: 'Car Aid Auto Collision', cat: 'Commercial Glass Installation', desc: 'Professional storefront glass installation and repair services across the shop facade.', loc: 'Scarborough', img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200' },
    { brand: 'Gracious Living', cat: 'Commercial Replacement', desc: 'Replacing glass in a commercial space. Custom-fabricated IGUs for an office retrofit.', loc: 'Mississauga', img: 'https://images.unsplash.com/photo-1577494096822-bfb9b3b82b56?w=1200' },
  ],
  processSteps: [
    { n: '01', t: 'Phone assessment', d: 'We ask about the type and size of break, whether anyone is injured, and if the property is secure. Helps us dispatch the right crew with the right materials.' },
    { n: '02', t: 'Rapid dispatch', d: 'A technician is dispatched immediately with target arrival of 30 to 60 minutes depending on your location in the GTA.' },
    { n: '03', t: 'On-site securing', d: 'Technician cleans up all broken glass, then secures the opening with a board-up (reinforced plywood or polycarbonate) or temporary glazing.' },
    { n: '04', t: 'Measure for permanent glass', d: 'Precise measurements are taken on-site so the replacement glass can be fabricated or sourced promptly.' },
    { n: '05', t: 'Follow-up installation', d: 'Once the permanent glass is ready, we schedule a return visit at a time convenient for you to complete the replacement.' },
  ],
  checklist: [
    { n: '01', t: 'Clear the area', d: 'Keep children, pets, and anyone without proper footwear away from the broken glass. Shards can scatter several feet from the break point.' },
    { n: '02', t: 'Don\'t touch attached glass', d: 'Glass still attached to the frame can fall without warning and cause deep cuts. Leave loose pieces alone until our technician arrives.' },
    { n: '03', t: 'Wear shoes and gloves', d: 'If you must walk near the area, wear closed-toe shoes and work gloves. Thin slippers or bare feet are a serious hazard.' },
    { n: '04', t: 'Cover the opening', d: 'Use a heavy tarp, thick cardboard, or plastic sheeting secured with tape to block wind, rain, and debris until we arrive.' },
    { n: '05', t: 'Photograph the damage', d: 'Take photos of the damage from both inside and outside. These help our technician prepare the right glass size and type before arriving.' },
    { n: '06', t: 'Call OhMyGlass', d: 'Call 647-803-2730. Our emergency line is staffed 24/7 including nights, weekends, and holidays.' },
  ],
  emTypes: [
    { ic: '01', t: 'Break-ins & vandalism', d: 'Shattered storefront glass, smashed residential windows, broken door glass. We secure and replace.' },
    { ic: '02', t: 'Storm damage', d: 'Windows broken by wind-borne debris, hail, or fallen tree branches. Weather-sealed same day.' },
    { ic: '03', t: 'Accidental impacts', d: 'Sports equipment, vehicle collisions, or objects thrown by lawn equipment. Fast turnaround.' },
    { ic: '04', t: 'Thermal stress cracks', d: 'Cracks that appear without visible impact, caused by extreme temperature differences between surface and edges.' },
    { ic: '05', t: 'Failed sealed units', d: 'A sudden crack in a double-pane window can leave one pane exposed and should be addressed promptly.' },
    { ic: '06', t: 'Commercial door glass', d: 'Broken entrance doors that prevent a business from opening or securing for the night.' },
  ],
  servicesForFooter: [
    ['Emergency Glass Repair', '/emergency-glass-repair'],
    ['Window Repair Toronto', '/window-repair-toronto'],
    ['Window Repair North York', '/window-repair-north-york'],
    ['Glass Replacement Toronto', '/glass-replacement-toronto'],
    ['Broken Window Repair', '/broken-window-repair'],
    ['Residential Window Repair', '/residential-window-repair'],
    ['Commercial Glass Repair', '/commercial-glass-repair'],
    ['Foggy Window Repair', '/foggy-window-repair'],
    ['Storefront Glass Repair', '/storefront-glass-repair'],
    ['Shower Glass Repair', '/shower-glass-repair'],
    ['Patio Door Repair', '/patio-door-repair'],
    ['Sliding Door Repair', '/sliding-door-repair'],
    ['Window & Door Hardware', '/window-and-door-hardware-repairs'],
    ['Window Glass Replacement', '/window-glass-replacement'],
    ['Double Pane Replacement', '/double-pane-window-replacement'],
  ],
};
