name               = "ohmyglass-agent"
main               = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
TO_EMAIL   = "info@ohmyglass.ca"
FROM_EMAIL = "hello@ednsy.com"

[observability]
[observability.logs]
enabled = false
invocation_logs = true

[observability.traces]
enabled = false
